'use client';

import React, { useState } from 'react';
import { BookOpen, ChevronDown, ChevronUp, Cpu, Key, Lock, ShieldCheck, AlertCircle } from 'lucide-react';

interface Topic {
  id: string;
  title: string;
  shortSummary: string;
  icon: any;
  securityGoal: 'Confidentiality' | 'Integrity' | 'Authenticity' | 'Freshness' | 'Key Derivation';
  mathematicalConcept: string;
  algorithmSpec: string;
  details: string[];
}

const TOPICS: Topic[] = [
  {
    id: 'sha256',
    title: 'SHA-256 Hashing & Canonical Representation',
    shortSummary: 'Transforms arbitrary-length canonical transaction strings into a deterministic 256-bit fixed-length cryptographic digest.',
    icon: Cpu,
    securityGoal: 'Integrity',
    mathematicalConcept: 'One-Way Hash Function H: {0,1}* → {0,1}^256 with Pre-image, Second Pre-image, and Collision Resistance.',
    algorithmSpec: 'FIPS 180-4 standard, 64-round Merkle-Damgård construction with 32-bit words and Davies-Meyer compression.',
    details: [
      'Avalanche Effect: Modifying even 1 single bit or comma in the transaction parameters changes approximately 50% of the output digest bits completely.',
      'Canonicalization: Prevents false positive hash mismatches caused by JSON key order shifts. Fields are sorted alphabetically and delimited with | before hashing.',
      'Crucial Distinction: Hashing is ONE-WAY and non-reversible. It does not provide confidentiality or encrypt data; it provides a fixed mathematical fingerprint.',
    ],
  },
  {
    id: 'ed25519',
    title: 'Ed25519 Digital Signatures',
    shortSummary: 'Asymmetric signature scheme based on Edwards-curve Digital Signature Algorithm (EdDSA) over Curve25519.',
    icon: Key,
    securityGoal: 'Authenticity',
    mathematicalConcept: 'Twisted Edwards curve -x² + y² = 1 - (121665/121666)x²y² over prime field 2^255 - 19.',
    algorithmSpec: 'RFC 8032 standard, 128-bit security level, SHA-512 internal hashing, 32-byte public keys, 64-byte deterministic signatures.',
    details: [
      'Signing: The sender uses their private key (stored safely in encrypted keystore) to sign the SHA-256 digest of the canonical transaction.',
      'Verification: Anyone (including the receiver and audit nodes) can verify with the sender’s public key that the signature was generated by the private key holder and the payload has not been modified.',
      'Non-Repudiation: The sender cannot later deny authorizing the transaction, as only their private key could have produced the signature.',
      'Crucial Distinction: Digital signatures do NOT hide or encrypt the transaction; they provide authenticity and proof of origin.',
    ],
  },
  {
    id: 'aes256gcm',
    title: 'AES-256-GCM Authenticated Encryption',
    shortSummary: 'Symmetric cipher operating in Galois/Counter Mode to provide both privacy and non-malleable integrity for sensitive memos.',
    icon: Lock,
    securityGoal: 'Confidentiality',
    mathematicalConcept: 'Rijndael block cipher substitution-permutation network combined with GHASH polynomial evaluation over GF(2^128).',
    algorithmSpec: 'NIST SP 800-38D, 256-bit symmetric key, 96-bit (12-byte) unique IV/nonce, 128-bit authentication tag.',
    details: [
      'Confidentiality: Plaintext memo is XORed with AES-generated keystream blocks, hiding the contents from eavesdroppers.',
      'Authenticity Tag: GCM computes a 128-bit GMAC authentication tag covering the ciphertext. If an attacker modifies even 1 bit of the ciphertext, decryption throws an immediate authentication failure.',
      'Nonce Safety: A freshly generated cryptographically random 96-bit IV is used for every encryption to avoid keystream reuse.',
    ],
  },
  {
    id: 'nonce_replay',
    title: 'Replay Protection & Nonce Freshness',
    shortSummary: 'Prevents valid intercepted transactions from being maliciously re-transmitted to duplicate payments.',
    icon: AlertCircle,
    securityGoal: 'Freshness',
    mathematicalConcept: 'Pseudo-Random Permutation (PRP) generating high-entropy 128-bit identifiers checked against a single-use registry.',
    algorithmSpec: '128-bit cryptographically secure random nonces + ACID transaction tracking with unique database constraints.',
    details: [
      'Why Signatures Alone Are Not Enough: A valid signature over a ₹500 transfer remains mathematically valid forever! An attacker who captures the wire packet could re-send it 100 times to drain the sender’s wallet.',
      'Dual Defense: Every transaction contains a unique TX-ID, an ISO timestamp, and a random 128-bit nonce.',
      'Single-Use Registry: The ledger stores consumed nonces inside a ProcessedNonce table. Resubmitted identical transactions are immediately rejected with REPLAY_DETECTED.',
    ],
  },
  {
    id: 'pbkdf2',
    title: 'PBKDF2-HMAC-SHA512 Password Key Derivation',
    shortSummary: 'Slow, salted, iterative cryptographic key derivation function preventing credential exposure and rainbow-table attacks.',
    icon: ShieldCheck,
    securityGoal: 'Key Derivation',
    mathematicalConcept: 'Iterated pseudo-random function: DK = PBKDF2(PRF, Password, Salt, c, dkLen) with c=100,000 rounds.',
    algorithmSpec: 'RFC 8018 / NIST SP 800-132, HMAC-SHA512, 16-byte random salt, 100,000 iterations, 64-byte (512-bit) key length.',
    details: [
      'Salt: 16 cryptographically secure random bytes prevent precomputed rainbow tables from cracking hashes of identical passwords.',
      'Work Factor: 100,000 HMAC rounds increase computational cost for attackers attempting brute-force or GPU dictionary attacks.',
      'Timing-Safe Comparison: Verification uses crypto.timingSafeEqual() to thwart side-channel timing attacks.',
    ],
  },
];

export default function AcademicExplanation() {
  const [openTopic, setOpenTopic] = useState<string | null>('sha256');

  return (
    <div className="bg-slate-900/60 border border-slate-800 rounded-xl p-5 my-6 backdrop-blur">
      <div className="flex items-center gap-2 mb-4 pb-3 border-b border-slate-800">
        <BookOpen className="w-5 h-5 text-cyan-400" />
        <div>
          <h3 className="text-sm font-bold text-slate-100 uppercase tracking-wider">
            Academic Cryptography Knowledge Base (Viva Reference)
          </h3>
          <p className="text-xs text-slate-400">
            Mathematical foundations and security goals distinguishing Confidentiality, Integrity, Authenticity, and Freshness.
          </p>
        </div>
      </div>

      <div className="space-y-3">
        {TOPICS.map((topic) => {
          const isOpen = openTopic === topic.id;
          const Icon = topic.icon;
          return (
            <div
              key={topic.id}
              className={`border rounded-lg transition-all ${
                isOpen ? 'border-cyan-500/40 bg-slate-950/70' : 'border-slate-800 bg-slate-950/30 hover:border-slate-700'
              }`}
            >
              <button
                onClick={() => setOpenTopic(isOpen ? null : topic.id)}
                className="w-full px-4 py-3 text-left flex items-center justify-between gap-3"
              >
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-lg bg-slate-900 border border-slate-800 flex items-center justify-center text-cyan-400">
                    <Icon className="w-4 h-4" />
                  </div>
                  <div>
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="font-semibold text-slate-200 text-xs sm:text-sm">{topic.title}</span>
                      <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-cyan-950/80 text-cyan-300 border border-cyan-800/60">
                        {topic.securityGoal}
                      </span>
                    </div>
                    <div className="text-[11px] text-slate-400 mt-0.5 line-clamp-1">{topic.shortSummary}</div>
                  </div>
                </div>
                {isOpen ? <ChevronUp className="w-4 h-4 text-slate-400" /> : <ChevronDown className="w-4 h-4 text-slate-400" />}
              </button>

              {isOpen && (
                <div className="px-4 pb-4 pt-2 border-t border-slate-800/80 space-y-3 text-xs text-slate-300">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3 bg-slate-900/80 p-3 rounded border border-slate-800/80">
                    <div>
                      <span className="text-[10px] uppercase font-mono text-cyan-400 font-bold block mb-1">
                        Mathematical Concept
                      </span>
                      <p className="text-[11px] font-mono text-slate-300">{topic.mathematicalConcept}</p>
                    </div>
                    <div>
                      <span className="text-[10px] uppercase font-mono text-emerald-400 font-bold block mb-1">
                        Algorithm Specification
                      </span>
                      <p className="text-[11px] font-mono text-slate-300">{topic.algorithmSpec}</p>
                    </div>
                  </div>

                  <ul className="space-y-1.5 list-disc pl-4 text-[11px] text-slate-300">
                    {topic.details.map((detail, idx) => (
                      <li key={idx} className="leading-relaxed">
                        {detail}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
